name: tests-tags
on:
  push:
    paths:
      - 'tags/**'
  pull_request:
    paths:
      - 'tags/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tags && npm install && npm run test:ci
